"""Pattern/signal definitions for child-safety risk categories.

Each entry:
  id          : unique identifier
  patterns    : list of lowercase keyword strings or regex patterns
  type        : "keyword" | "regex"
  weight      : float 1.0-10.0  contribution to category score
  description : what this pattern detects
  fp_risk     : common false-positive scenarios

Keyword patterns use word-boundary matching on lowercased text.
Regex patterns are compiled with re.IGNORECASE.
"""

SELF_HARM = [
    {"id": "sh_direct_statement",
     "patterns": ["i want to die", "i want to kill myself", "i wish i was dead",
                  "i want to end it", "better off dead", "i should just die",
                  "i want to end my life", "i feel like ending it",
                  "i want to disappear forever", "i don't want to be alive",
                  "i don't want to live anymore", "i wish i could die",
                  "i'm going to kill myself", "i plan to kill myself",
                  "thinking about suicide", "suicidal thoughts",
                  "i just want to stop existing", "i don't belong in this world"],
     "type": "keyword", "weight": 9.0,
     "description": "Direct statements of suicidal ideation or intent",
     "fp_risk": "Lyrics, quotes, fiction, or educational discussion"},
    {"id": "sh_method",
     "patterns": ["i have pills", "bought a rope", "got a knife",
                  "going to jump", "i found a way", "have a plan to end it",
                  "stockpiling pills", "how many pills", "tie a noose",
                  "bought a gun", "loaded the gun"],
     "type": "keyword", "weight": 9.5,
     "description": "Mention of specific self-harm or suicide method",
     "fp_risk": "News discussion, fiction, educational context"},
    {"id": "sh_harm_behavior",
     "patterns": ["cut myself", "cutting myself", "self harm", "self-harm",
                  "hurting myself", "burned myself", "made myself bleed",
                  "i self harm", "i cut myself", "i cut again", "harming myself",
                  "scratching myself", "hit myself", "banging my head"],
     "type": "keyword", "weight": 8.0,
     "description": "Current or recent self-harm behavior",
     "fp_risk": "Past tense discussion, recovery sharing, educational"},
    {"id": "sh_farewell",
     "patterns": ["this is goodbye", "i won't be here tomorrow",
                  "i'm saying goodbye", "tell everyone i'm sorry",
                  "my last message", "i won't see you again",
                  "this is the last time", "when i'm gone",
                  "don't forget me when i'm gone"],
     "type": "keyword", "weight": 9.5,
     "description": "Farewell or final messages indicating imminent action",
     "fp_risk": "Dramatic statements in fiction or role-play"},
    {"id": "sh_hopelessness",
     "patterns": ["nothing matters anymore", "life is pointless",
                  "there's no hope", "i give up", "what's the point",
                  "nobody cares", "i'm a burden", "everyone would be better off",
                  "no reason to live", "i hate my life",
                  "my life is worthless", "i'm hopeless",
                  "things will never get better", "what's the point anymore"],
     "type": "keyword", "weight": 5.0,
     "description": "Expressions of hopelessness or despair",
     "fp_risk": "General frustration, teenage angst, song lyrics"},
    {"id": "sh_planning",
     "patterns": ["i've been planning", "my plan is", "i wrote a note",
                  "figured out how", "i know exactly how", "made arrangements",
                  "settled my affairs", "said my goodbyes"],
     "type": "keyword", "weight": 9.0,
     "description": "Evidence of suicide planning or preparation",
     "fp_risk": "Discussion about a fictional character or news story"},
    {"id": "sh_recent_attempt",
     "patterns": ["tried to kill myself", "attempted suicide",
                  "tried to end it", "survived an attempt",
                  "was in the hospital", "they stopped me",
                  "overdosed", "took too many pills"],
     "type": "keyword", "weight": 9.0,
     "description": "Reference to a recent or past suicide attempt",
     "fp_risk": "Recovery narrative, support group discussion"},
    {"id": "sh_help_seeking_crisis",
     "patterns": ["i need help", "please help me", "i don't know what to do",
                  "i'm scared", "i can't do this anymore",
                  "i can't take it anymore", "i'm falling apart",
                  "i'm breaking down", "i'm losing my mind",
                  "i can't cope", "i'm not okay"],
     "type": "keyword", "weight": 4.0,
     "description": "General crisis or help-seeking statements",
     "fp_risk": "General stress, academic pressure, everyday frustration"},
    {"id": "sh_contagion",
     "patterns": ["i want to be with", "i'll be with them soon",
                  "i want to join them"],
     "type": "keyword", "weight": 7.0,
     "description": "Reference to joining someone who died by suicide",
     "fp_risk": "Grief expression, religious discussion"},
]

GROOMING = [
    {"id": "gr_secrecy",
     "patterns": ["don't tell anyone", "keep this between us",
                  "our little secret", "don't tell your parents",
                  "don't tell mom", "don't tell dad",
                  "just between you and me", "this stays between us",
                  "don't mention this to", "they wouldn't understand",
                  "what happens here stays here"],
     "type": "keyword", "weight": 7.0,
     "description": "Requests for secrecy or hidden communication",
     "fp_risk": "Friends sharing secrets, game-related confidentiality"},
    {"id": "gr_age_deception",
     "patterns": ["i'm younger than i said", "don't worry about my age",
                  "age is just a number", "what matters is how we feel",
                  "i know i look young but"],
     "type": "keyword", "weight": 8.0,
     "description": "Age deception or minimization of age difference",
     "fp_risk": "Honest age correction"},
    {"id": "gr_private_channel",
     "patterns": ["let's talk on", "message me on", "add me on",
                  "let's go private", "switch to", "my number is",
                  "what's your snap", "what's your insta",
                  "let's move to dm", "dm me", "private message me",
                  "chat off this app", "let's use"],
     "type": "keyword", "weight": 6.0,
     "description": "Attempts to move conversation to a private or encrypted channel",
     "fp_risk": "Normal social media connection between peers"},
    {"id": "gr_gifts",
     "patterns": ["i'll buy you", "i got you a", "i can send you",
                  "want me to get you", "i'll give you money",
                  "i can get you anything", "gift card", "i sent you",
                  "let me treat you", "i'll pay for",
                  "i have a present for you"],
     "type": "keyword", "weight": 5.0,
     "description": "Offers of gifts, money, or treats",
     "fp_risk": "Parental/family offers, legitimate friendship gifts"},
    {"id": "gr_meeting",
     "patterns": ["let's meet", "come over", "where do you live",
                  "let's get together", "i can pick you up",
                  "meet me at", "i'll come get you",
                  "can i see you", "want to hang out alone",
                  "when can i see you", "let's go somewhere private",
                  "i'll find you", "don't bring anyone"],
     "type": "keyword", "weight": 7.0,
     "description": "Attempts to arrange in-person meetings, especially private",
     "fp_risk": "Normal friendship plans between peers"},
    {"id": "gr_sexualization",
     "patterns": ["are you a virgin", "have you ever had sex",
                  "send me a picture", "show me your body",
                  "you look older", "you're so mature for your age",
                  "you're not like other kids", "you're very mature",
                  "nobody understands you like i do",
                  "you can trust me more than"],
     "type": "keyword", "weight": 8.0,
     "description": "Sexualization or premature romantic/sexual topics",
     "fp_risk": "Age-appropriate sex education questions between peers"},
    {"id": "gr_isolation",
     "patterns": ["your friends don't care", "your family doesn't understand",
                  "nobody gets you like i do", "they're just using you",
                  "i'm the only one who really cares",
                  "you don't need anyone else", "just forget about them",
                  "they don't deserve you"],
     "type": "keyword", "weight": 6.5,
     "description": "Attempts to isolate child from friends or family",
     "fp_risk": "Normal conflict with friends expressed to a trusted adult"},
    {"id": "gr_threats",
     "patterns": ["if you tell", "don't you dare say", "nobody will believe you",
                  "i'll deny everything", "you'll get in trouble too",
                  "they'll take your phone", "they'll blame you",
                  "you want this too", "you started it",
                  "i have your pictures", "i'll share them"],
     "type": "keyword", "weight": 9.0,
     "description": "Threats, blackmail, or coercion to maintain secrecy",
     "fp_risk": "Peer conflict, non-grooming related threats"},
    {"id": "gr_relationship_claim",
     "patterns": ["i love you", "i need you", "you belong to me",
                  "i can't live without you", "you're mine",
                  "we have something special", "this is our thing",
                  "nobody can love you like i do"],
     "type": "keyword", "weight": 6.0,
     "description": "Emotional dependency or exclusive relationship claims",
     "fp_risk": "Peer romantic relationships, family expressions"},
]

BULLYING = [
    {"id": "bu_name_calling",
     "patterns": ["you're a loser", "you're stupid", "you're dumb",
                  "nobody likes you", "you're ugly", "you're worthless",
                  "you're a joke", "you're pathetic", "you're trash",
                  "you're a failure", "you're annoying", "you're weird",
                  "you're so dumb", "you're so stupid", "you're a freak"],
     "type": "keyword", "weight": 5.0,
     "description": "Direct name-calling and insults",
     "fp_risk": "Friendly banter, mutual teasing, heated argument"},
    {"id": "bu_threats",
     "patterns": ["i'm going to get you", "you're going to pay",
                  "i'll find you", "you better watch out",
                  "after school", "i'll beat you up",
                  "i'm going to hurt you", "you're dead",
                  "i'll mess you up", "gonna get you"],
     "type": "keyword", "weight": 7.0,
     "description": "Physical threats and intimidation",
     "fp_risk": "Exaggerated language, game talk, role-play"},
    {"id": "bu_exclusion",
     "patterns": ["you can't sit with us", "nobody wants you here",
                  "go away", "leave us alone", "you're not invited",
                  "don't come", "we don't want you", "you're not welcome",
                  "just leave", "nobody wants to be your friend"],
     "type": "keyword", "weight": 4.5,
     "description": "Social exclusion and rejection",
     "fp_risk": "Normal group boundary setting, conflict"},
    {"id": "bu_coordinated",
     "patterns": ["everyone hates you", "the whole class", "we all think",
                  "tell them too", "everyone says", "everyone knows",
                  "the group decided", "we all agree"],
     "type": "keyword", "weight": 6.0,
     "description": "Coordinated or group bullying indicators",
     "fp_risk": "Group decision making in benign contexts"},
    {"id": "bu_rumors",
     "patterns": ["did you hear about", "i heard that", "everyone's talking about",
                  "spread the word", "let's tell everyone", "post it everywhere",
                  "i'm going to share", "wait until everyone finds out"],
     "type": "keyword", "weight": 5.0,
     "description": "Spreading rumors or private information",
     "fp_risk": "Normal gossip, news sharing"},
    {"id": "bu_humiliation",
     "patterns": ["take a picture", "record this", "put it online",
                  "let's film", "everyone should see",
                  "post this everywhere", "share this",
                  "let's make a video of"],
     "type": "keyword", "weight": 6.5,
     "description": "Attempts to record or publicly humiliate",
     "fp_risk": "Normal video/photo sharing among friends"},
    {"id": "bu_doxxing",
     "patterns": ["i know where you live", "i know your address",
                  "i'm going to tell everyone", "i'll expose you",
                  "i'll post your", "everyone will know about",
                  "i have your info"],
     "type": "keyword", "weight": 8.0,
     "description": "Threats to expose personal information",
     "fp_risk": "Exaggerated conflict language"},
    {"id": "bu_identity",
     "patterns": ["faking", "pretending to be", "i made an account",
                  "let's catfish", "they won't know it's me",
                  "impersonate", "fake profile"],
     "type": "keyword", "weight": 7.0,
     "description": "Impersonation or identity deception for harassment",
     "fp_risk": "Discussion of online safety, educational content"},
]

SEXUAL_EXPLOITATION = [
    {"id": "se_referencing_minor",
     "patterns": ["young girl", "young boy", "underage", "minor",
                  "barely legal", "jailbait", "just turned 18",
                  "teen pics", "child pics"],
     "type": "keyword", "weight": 9.0,
     "description": "Content referencing minors in exploitative context",
     "fp_risk": "Age-appropriate conversation about children, news"},
    {"id": "se_image_request",
     "patterns": ["send nudes", "send pics", "naked picture",
                  "underwear pic", "photo of you without",
                  "send me a picture of yourself", "show me your body",
                  "take a picture of yourself", "explicit photo",
                  "send me something sexy", "a picture of you"],
     "type": "keyword", "weight": 9.0,
     "description": "Requests for intimate images from a minor",
     "fp_risk": "Request for non-intimate photos, peer sexting"},
    {"id": "se_sextortion",
     "patterns": ["i have your pictures", "i have your nudes",
                  "i'll send these to", "pay me or i'll",
                  "if you don't send", "your parents will see",
                  "everyone will see", "i'll post them",
                  "you don't want these getting out"],
     "type": "keyword", "weight": 10.0,
     "description": "Sextortion threats using intimate images",
     "fp_risk": "None — this indicates a severe safeguarding situation"},
    {"id": "se_sexual_explicit_minor",
     "patterns": ["what are you wearing", "are you a virgin",
                  "do you touch yourself", "have you ever had sex",
                  "do you want to try", "i can teach you",
                  "let me show you", "do you like older",
                  "it's ok if you're young"],
     "type": "keyword", "weight": 9.5,
     "description": "Explicit sexual conversation topics directed at a minor",
     "fp_risk": "Sex ed discussion between peers of similar age"},
    {"id": "se_transaction",
     "patterns": ["how much for", "i'll pay you for", "for money",
                  "i can give you money", "in exchange for",
                  "you'll get paid", "i'll give you",
                  "for a price"],
     "type": "keyword", "weight": 8.0,
     "description": "Transactional offers for sexual content or acts",
     "fp_risk": "Normal commerce discussions"},
    {"id": "se_manipulation_exploit",
     "patterns": ["i know you're lonely", "i can be your boyfriend",
                  "you need someone who", "i understand you better than",
                  "no one else will", "you're lucky i'm here",
                  "i'm your only friend", "nobody else cares"],
     "type": "keyword", "weight": 6.0,
     "description": "Emotional exploitation of vulnerability",
     "fp_risk": "Supportive friendship, emotional support"},
    {"id": "se_roleplay_adult",
     "patterns": ["pretend we're", "let's roleplay", "rp with me",
                  "imagine you're", "let's pretend", "fantasy"],
     "type": "keyword", "weight": 4.0,
     "description": "Role-play requests (context dependent)",
     "fp_risk": "Normal imaginative play, gaming, fiction writing"},
]

VIOLENCE = [
    {"id": "vi_direct_threat",
     "patterns": ["i'm going to kill you", "i'm going to hurt you",
                  "i'm going to stab you", "i'm going to shoot you",
                  "i'm going to beat you", "i'll break your",
                  "i'm going to destroy you", "i'll smash your",
                  "i'll slit your", "i'll cut your",
                  "going to punch", "going to attack",
                  "i'm going to end you"],
     "type": "keyword", "weight": 8.5,
     "description": "Direct threats of physical violence",
     "fp_risk": "Exaggerated language, game chat, jokes among friends"},
    {"id": "vi_weapon",
     "patterns": ["bringing a gun", "got a knife", "i have a weapon",
                  "i'll get my dad's gun", "brought a knife to school",
                  "i have a bat", "loaded gun", "sharp object",
                  "i have a gun"],
     "type": "keyword", "weight": 9.0,
     "description": "Weapon possession or acquisition references",
     "fp_risk": "Hunting discussion, video game context"},
    {"id": "vi_school_violence",
     "patterns": ["shoot up the school", "bomb the school",
                  "attack the school", "bring a gun to school",
                  "school shooting", "planning an attack",
                  "don't come to school tomorrow"],
     "type": "keyword", "weight": 10.0,
     "description": "References to school-based violence or attacks",
     "fp_risk": "News discussion, fiction, dark humor"},
    {"id": "vi_fight_planning",
     "patterns": ["meet me after school", "fight me", "let's settle this",
                  "i'll be waiting", "you know where to find me",
                  "bring your friends", "we'll be there",
                  "after class", "in the parking lot"],
     "type": "keyword", "weight": 6.0,
     "description": "Arranging physical confrontations",
     "fp_risk": "Normal conflict resolution, sports context"},
    {"id": "vi_violent_ideation",
     "patterns": ["i want to hurt someone", "i want to hurt them",
                  "i want to make them pay", "they deserve to die",
                  "i want to see them suffer", "i want blood",
                  "i want revenge", "they need to pay"],
     "type": "keyword", "weight": 7.0,
     "description": "Violent ideation or desire for revenge",
     "fp_risk": "Movie/TV discussion, emotional venting, fiction"},
    {"id": "vi_detailed_plan",
     "patterns": ["first i'll", "then i'll", "after that i'll",
                  "i've mapped out", "i've been watching",
                  "i know their schedule", "i know when",
                  "this is how i'll do it"],
     "type": "keyword", "weight": 8.0,
     "description": "Detailed planning of violent acts",
     "fp_risk": "Fiction writing, game strategy, project planning"},
]

PII_EXPOSURE = [
    {"id": "pii_email",
     "patterns": [r"\b[\w.%-]+@[\w.-]+\.\w{2,}\b"],
     "type": "regex", "weight": 5.0,
     "description": "Email address exposure",
     "fp_risk": "Legitimate use (sign-up, contact sharing)"},
    {"id": "pii_phone",
     "patterns": [r"\b\d{3}[-.]?\d{3}[-.]?\d{4}\b",
                  r"\b\d{3}[-.]?\d{4}\b"],
     "type": "regex", "weight": 7.0,
     "description": "Phone number exposure",
     "fp_risk": "Legitimate contact sharing"},
    {"id": "pii_ssn",
     "patterns": [r"\b\d{3}-\d{2}-\d{4}\b"],
     "type": "regex", "weight": 9.0,
     "description": "Social Security Number exposure",
     "fp_risk": "Legitimate use in rare contexts"},
    {"id": "pii_address",
     "patterns": [r"\b\d{1,5}\s+[A-Za-z]+\s+(?:Street|St|Avenue|Ave|Road|Rd|Boulevard|Blvd|Drive|Dr|Lane|Ln|Court|Ct|Place|Pl|Circle|Cir)\b"],
     "type": "regex", "weight": 7.0,
     "description": "Street address exposure",
     "fp_risk": "Legitimate use"},
    {"id": "pii_credit_card",
     "patterns": [r"\b(?:\d{4}[-\s]?){3}\d{4}\b"],
     "type": "regex", "weight": 9.0,
     "description": "Credit/debit card number exposure",
     "fp_risk": "False positive on long number sequences"},
    {"id": "pii_name_context",
     "patterns": ["my name is", "i am called", "call me",
                  "my full name is", "my real name is",
                  "people call me"],
     "type": "keyword", "weight": 3.0,
     "description": "Context indicators for name disclosure",
     "fp_risk": "Normal self-introduction"},
    {"id": "pii_school_context",
     "patterns": ["i go to", "my school is", "i attend",
                  "in grade", "in year", "my teacher is",
                  "class of", "i'm in", "my homeroom"],
     "type": "keyword", "weight": 4.0,
     "description": "School name or location disclosure",
     "fp_risk": "Normal conversation about school"},
    {"id": "pii_dob",
     "patterns": [r"\b\d{1,2}/\d{1,2}/\d{2,4}\b"],
     "type": "regex", "weight": 5.0,
     "description": "Date of birth exposure (MM/DD/YYYY pattern)",
     "fp_risk": "Normal date references"},
]

DISCRIMINATION = [
    {"id": "di_hate_group",
     "patterns": [r"all\s+\w+\s+should\s+", r"\w+\s+are\s+inferior",
                  r"\w+\s+don't\s+deserve\s+", r"get\s+rid\s+of\s+all\s+",
                  "deport them all", "master race",
                  "pure race", "white power"],
     "type": "regex", "weight": 8.5,
     "description": "Hate group ideology and genocidal rhetoric",
     "fp_risk": "Historical discussion, news analysis, academic context"},
    {"id": "di_targeted_hate",
     "patterns": [r"you\s+\w+\s+people", "people like you",
                  "your kind", "you're a disgrace to",
                  "you don't belong here", "go back to your country",
                  "go back where you came from"],
     "type": "regex", "weight": 7.0,
     "description": "Direct targeted hate speech",
     "fp_risk": "Political discussion, heated argument"},
    {"id": "di_disability_hate",
     "patterns": ["retard", "mong", "spaz",
                  "cripple", "midget"],
     "type": "keyword", "weight": 6.0,
     "description": "Disability-based slurs",
     "fp_risk": "Quotation, education, reclamation"},
    {"id": "di_religious_hate",
     "patterns": [r"all\s+\w+\s+are\s+terrorists", r"\w+\s+is\s+evil",
                  r"ban\s+\w+", r"\w+\s+should\s+be\s+illegal"],
     "type": "regex", "weight": 6.0,
     "description": "Religious intolerance and hate",
     "fp_risk": "Theological debate, news discussion"},
]

DISTRESS = [
    {"id": "ds_acute_distress",
     "patterns": ["i can't breathe", "i'm having a panic attack",
                  "i can't stop crying", "i'm shaking uncontrollably",
                  "i feel like i'm dying", "my heart is racing",
                  "i can't calm down", "i'm hyperventilating",
                  "i feel like i'm losing control"],
     "type": "keyword", "weight": 7.0,
     "description": "Acute emotional or physiological distress",
     "fp_risk": "Exaggerated language, exercise related"},
    {"id": "ds_emotional_pain",
     "patterns": ["i'm so broken", "i feel empty", "i'm numb",
                  "it hurts so much", "i can't feel anything",
                  "i'm drowning", "i'm suffocating",
                  "i feel dead inside", "the pain is too much",
                  "i just want the pain to stop"],
     "type": "keyword", "weight": 6.0,
     "description": "Emotional pain and suffering expressions",
     "fp_risk": "Song lyrics, fiction, figurative expression"},
    {"id": "ds_self_loathing",
     "patterns": ["i hate myself", "i'm disgusting", "i'm a terrible person",
                  "i don't deserve to", "i'm a mistake",
                  "i'm worthless", "i'm not good enough",
                  "i hate who i am", "i'm a disappointment",
                  "i'm such a failure"],
     "type": "keyword", "weight": 5.0,
     "description": "Intense self-criticism and self-loathing",
     "fp_risk": "General low self-esteem, teenage angst"},
    {"id": "ds_crisis_statement",
     "patterns": ["i don't know what to do", "i need someone to talk to",
                  "i can't handle this", "everything is falling apart",
                  "my life is falling apart", "i need help right now",
                  "i'm scared of myself", "i don't feel safe",
                  "something bad is going to happen"],
     "type": "keyword", "weight": 6.5,
     "description": "Crisis statements indicating escalating situation",
     "fp_risk": "General life stress, academic pressure"},
    {"id": "ds_abuse_disclosure",
     "patterns": ["they hit me", "they hurt me", "i'm being abused",
                  "they touched me", "i didn't want it",
                  "they made me do", "i'm scared to go home",
                  "i can't go home", "they're hurting me",
                  "nobody believes me"],
     "type": "keyword", "weight": 9.0,
     "description": "Disclosure of ongoing abuse or harm",
     "fp_risk": "Fiction, discussion of past events, news"},
    {"id": "ds_urgent_safety",
     "patterns": ["i'm not safe", "i'm in danger", "someone is following me",
                  "i'm trapped", "please come get me",
                  "i need to get out", "i can't stay here",
                  "help me please", "call the police",
                  "send help", "emergency", "i need an ambulance"],
     "type": "keyword", "weight": 9.0,
     "description": "Urgent safety concerns requiring immediate response",
     "fp_risk": "Game context, role-play, movie references"},
]

PATTERNS = {
    "self_harm": SELF_HARM,
    "grooming": GROOMING,
    "bullying": BULLYING,
    "sexual_exploitation": SEXUAL_EXPLOITATION,
    "violence": VIOLENCE,
    "pii_exposure": PII_EXPOSURE,
    "discrimination": DISCRIMINATION,
    "distress": DISTRESS,
}

CATEGORY_WEIGHTS = {
    "self_harm": 1.2,
    "grooming": 1.1,
    "bullying": 1.0,
    "sexual_exploitation": 1.3,
    "violence": 1.1,
    "pii_exposure": 0.8,
    "discrimination": 1.0,
    "distress": 1.0,
}

CATEGORY_DESCRIPTIONS = {
    "self_harm": "Self-harm and suicide risk",
    "grooming": "Grooming and exploitation indicators",
    "bullying": "Bullying and harassment",
    "sexual_exploitation": "Sexual exploitation and CSAM",
    "violence": "Violence and threats",
    "pii_exposure": "Personal information exposure",
    "discrimination": "Discrimination and hate speech",
    "distress": "Distress and emotional crisis",
}
